version: 2.1
orbs:
  cypress: cypress-io/cypress@1.13.0
jobs:
  build:
    docker:
      - image: circleci/node:10.13-browsers
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
  test:
    docker:
      - image: circleci/node:10.13-browsers
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run tslint
      - run: npm run test -- --ci --runInBand
workflows:
  version: 2
  test-all:
    jobs:
      - build
      - test:
        requires:
          - build
