version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.13-browsers
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run tslint
      - run: npm run test -- --ci --runInBand
